export * from './movie-list/movie-list.component';
export * from './movie/movie.component';
export * from './footer/footer.component';
export * from './header/header.component';
export * from './favmovies/favmovies.component';
export * from './not-found/not-found.component';
export * from './signin/signin.component';
export * from './signup/signup.component';
export * from './modal/modal.component';
